### ISSUE TITLE
Low frame rate during some fights

### ISSUE THREAD

**Issue by Ricky-James** [erickt420/FFXCutsceneRemover#35]
For example Seymour/Anima, and Home Chimeras

**Comment by fkelava** [comment]
This is fixable by setting ``FFX.exe+8E9004 (PTR, offset 1C) = 0``, which will disable the timing system that governs these cutscenes. This would normally result in VA desync but since the cutscenes are skipped anyway in CS%, this defect is not visible.

I've informed Crimson and this will be included in the next release. This method fixes Seymour and Home Chimeras.

**Comment by fkelava** [comment]
The fix is present in #39. You can close this issue.
