### ISSUE TITLE
Skip cutscenes using Pause + Square

### ISSUE THREAD

**Issue by flobberworm4** [erickt420/FFXCutsceneRemover#5]
At the moment we skip cutscenes automatically as we screen transition/hit certain triggers in the game. For a full cutscene skip mod experience, would be nice if the user had the option to skip cutscenes by pressing Pause + Square like some FMVs currently are skipped.

This would involve a change in design in the code, e.g. rather than iterating through a loop constantly looking for values, simply look for the combined sequence of buttons and then find the most appropriate skip in the Transitions dictionary.

Advantage is it gives a fuller experience and allows casual players to enjoy the mod, and also be useful for speedrunners to practice manual skips in the game. 

Disadvantage is not every cutscene has the ability to pause in them, and this will involve a lot of rework to individualise each skip rather than bulk skip several at once like we do currently.

**Comment by Ricky-James** [comment]
Feel free to re-open this issue but I think we've decided against implementing this one.
Runners seem to like the automatic skips and, with the leaderboards, we would have to scrap all of the times that exist if this were to get added since it would add a fairly significant amount of time to the run.
