### ISSUE TITLE
Black screens after non-scripted battles

### ISSUE THREAD

**Issue by Michelrpg** [erickt420/FFXCutsceneRemover#50]
- After every fight post-scripted fights (encounters with rikku underwater, encounters with wakka) the screen just turns full black. Victory fanfare keeps playing.  If the black screen goes away its immediately met with another combat phase (not sure if this is because I move during the black screen or not?).

- I have no menu access whatsoever. It just wont respond.

Happens with both normal and expert sphere grid choices.

(edit)

I tried running the game without the program to make sure its not the installation, and it runs perfectly without it. No clue what this is about

**Comment by Ricky-James** [comment]
Only really heard of this issue in isolated cases, it's strange to hear it happening consistently.

Are you using the Steam version?
Are you using any speed-up (either through cheatengine or x4 booster)?
A video demonstrating the issue would be super helpful

**Comment by Michelrpg** [comment]
I am using the steam version. No additional programs, edits whatsoever are used other than the cutscene skip running in the background. I play the game as it was intended.

I'll make a recording on twitch on whats happening tomorrow.

**Comment by Michelrpg** [comment]
So... I made a video. 3 actually (had to cut one mid-run due to a phone call).

The first one ran into an entirely different bug where the tanker just would not be destroyed. I dealt an absolutely ridiculous amount of damage to it, it just wouldnt die. So I restarted that run.

https://www.twitch.tv/videos/1433321460 (fight in question begins after 10 minute mark)

The second run went.. flawless. I actually had no troubles with black screens, I had no breaking issues with anything. However, I did encounter moments where the audio carried over, or was gone altogether, and the visual "bug" with Tidus holding his sword after the fight against the squid monster underwater.

Here are the two videos of the second run:

https://www.twitch.tv/videos/1433333448 (cuts off between klikk fight)
https://www.twitch.tv/videos/1433343833 (nothing happened in the fight, just cut stream for the phone call)


On one hand Im kind of happy the game continued as it should have, on the other hand Im kind of disappointed because I couldnt capture the issue. But apparantly I ran into another bug so.. win I guess?

**Comment by Ricky-James** [comment]
The tanker fight has very unique mechanics that aren't fully understood, but in short, it doesn't die to damage like traditional enemies (in fact it heals to full every turn). The damage you deal does have some impact in determining how many turns it takes to kill though, and I believe the reason you were stuck is because you rolled such low strength on the randomiser.

I wouldn't necessarily call this a bug, since it's just how the game is intended to behave, but it is arguably an oversight with the randomiser, and it's probably a good idea for the randomiser to introduce a failsafe to ensure you can pass Tanker with low stats. However, I don't think randomiser issues are really being tracked right now since it's in an early development stage.

The music and visual bugs are known issues (#37 & #29) but aren't a high priority.

**Comment by Ricky-James** [comment]
Closing issue since there's no evidence of black screen (perhaps not a CSR issue).
Other issue discussed is with randomizer, not CSR.
