### ISSUE TITLE
Soft reset during battles and FMVs

### ISSUE THREAD

**Issue by flobberworm4** [erickt420/FFXCutsceneRemover#6]
At the moment the soft reset can only be used in the open world or during cutscenes. Would be nice if it was supported in some way during battles and during FMVs to match the PS2 version.

**Comment by Ricky-James** [comment]
I'm gonna close this because I think it'd be risky to implement any soft reset. Could affect routes and encounter manip depending on how the soft reset works.
If we ever find a disabled function or something that we can call in the game that does it, that'd be cool, but I think implementing a hacky soft-reset is likely to just cause headaches
